x-extras: &extras
  restart: unless-stopped
  networks:
    - clickhouse
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

services:
  clickhouse:
    container_name: clickhouse
    image: ${INST_CLICKHOUSE_IMAGE}
    env_file:
      - common.env
      - clickhouse.env
    ports:
      - "9000:9000" # Client port
      - "8123:8123" # HTTP port
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 4G
    <<: *extras

networks:
  clickhouse:
    name: clickhouse
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.254
