x-extras: &extras
  restart: unless-stopped
  networks:
    - public
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

services:
  grafana:
    image: ${INST_PGADMIN_IMAGE}
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    env_file:
      - common.env
      - grafana.env
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${INST_GRAFANA_PASSWORD}
      GF_DATABASE_PASSWORD: ${INST_POSTGRESQL_PASSWORD}
    volumes:
      - ${INST_GRAFANA_DIR}/data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 16G
    depends_on:
      grafana-postgres:
        condition: service_healthy
    <<: *extras

  grafana-postgres:
    image: ${INST_POSTGRESQL_IMAGE}
    container_name: grafana-postgres
    # ports:
    #   - 5432:5432
    volumes:
      - ${INST_POSTGRESQL_DIR}/data:/var/lib/postgresql/data
    env_file:
      - common.env
      - postgres.env
    environment:
      POSTGRES_PASSWORD: ${INST_POSTGRESQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 4G
    shm_size: '256m'
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    <<: *extras

networks:
  public:
    name: public
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.254
